version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    volumes:
      - gp_data:/var/lib/mysql

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://IP:8081/api/
    ports:
      - "3000:80"

  backend:
    build: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://IP:3307/db?useUnicode=true&useJDBCCompliantTimeZoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KEYCLOAK_URL=https://url
      - SPRING_KEYCLOAK_USERNAME=
      - SPRING_KEYCLOAK_PASSWORD=
      - SPRING_KEYCLOAK_SECRET=
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  gp_data:
